/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author kikev
 */
public class Calculadora2 extends javax.swing.JFrame {

    double operando1 = 0; //Guarda el primer número introducido.
    String operacion = ""; //Guarda la operación seleccionada.
    
    public Calculadora2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pantalla = new javax.swing.JLabel();
        siete = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        uno1 = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        division = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        coma = new javax.swing.JButton();
        signoCambiado = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        inversa = new javax.swing.JButton();

        jButton1.setText("+");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Consolas", 0, 40)); // NOI18N
        pantalla.setForeground(new java.awt.Color(51, 255, 51));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 277, 56));

        siete.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        siete.setText("7");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        getContentPane().add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 151, 64, 64));

        nueve.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        getContentPane().add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 151, 64, 64));

        ocho.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        getContentPane().add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 151, 64, 64));

        seis.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 222, 64, 64));

        cinco.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        getContentPane().add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 222, 64, 64));

        cuatro.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        getContentPane().add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 222, 64, 64));

        cero.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        getContentPane().add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 364, 64, 64));

        tres.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        getContentPane().add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 293, 64, 64));

        dos.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        getContentPane().add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 293, 64, 64));

        uno1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        uno1.setText("1");
        uno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uno1ActionPerformed(evt);
            }
        });
        getContentPane().add(uno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 293, 64, 64));

        multiplicacion.setBackground(new java.awt.Color(153, 153, 153));
        multiplicacion.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        multiplicacion.setText("X");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 151, 64, 64));

        resta.setBackground(new java.awt.Color(153, 153, 153));
        resta.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        getContentPane().add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 222, 64, 64));

        division.setBackground(new java.awt.Color(153, 153, 153));
        division.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        getContentPane().add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 80, 64, 64));

        igual.setBackground(new java.awt.Color(153, 153, 153));
        igual.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 364, 64, 64));

        suma.setBackground(new java.awt.Color(153, 153, 153));
        suma.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        getContentPane().add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 293, 64, 64));

        coma.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        coma.setText(",");
        coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaActionPerformed(evt);
            }
        });
        getContentPane().add(coma, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 364, 64, 64));

        signoCambiado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        signoCambiado.setText("+/-");
        signoCambiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoCambiadoActionPerformed(evt);
            }
        });
        getContentPane().add(signoCambiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 364, 64, 64));

        raiz.setBackground(new java.awt.Color(153, 153, 153));
        raiz.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        raiz.setText("√");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        getContentPane().add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 80, 64, 64));

        potencia.setBackground(new java.awt.Color(153, 153, 153));
        potencia.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        potencia.setText("^");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });
        getContentPane().add(potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 80, 64, 64));

        inversa.setBackground(new java.awt.Color(153, 153, 153));
        inversa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inversa.setText("1/x");
        inversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inversaActionPerformed(evt);
            }
        });
        getContentPane().add(inversa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 64, 64));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed

        String auxiliar = pantalla.getText();
        pantalla.setText(auxiliar + "7");
        if (auxiliar.equals ("0")){
        pantalla.setText("7");
        }
        else{
        pantalla.setText(auxiliar + "7");
        }
    }//GEN-LAST:event_sieteActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "9");        if (auxiliar.equals ("0")){        pantalla.setText("9");        }        else{        pantalla.setText(auxiliar + "9");        }
    }//GEN-LAST:event_nueveActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "8");        if (auxiliar.equals ("0")){        pantalla.setText("8");        }        else{        pantalla.setText(auxiliar + "8");        }
    }//GEN-LAST:event_ochoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "6");        if (auxiliar.equals ("0")){        pantalla.setText("6");        }        else{        pantalla.setText(auxiliar + "6");        }
    }//GEN-LAST:event_seisActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "5");        if (auxiliar.equals ("0")){        pantalla.setText("5");        }        else{        pantalla.setText(auxiliar + "5");        }
    }//GEN-LAST:event_cincoActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "4");        if (auxiliar.equals ("0")){        pantalla.setText("4");        }        else{        pantalla.setText(auxiliar + "4");        }
    }//GEN-LAST:event_cuatroActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "0");        if (auxiliar.equals ("0")){        pantalla.setText("0");        }        else{        pantalla.setText(auxiliar + "0");        }
    }//GEN-LAST:event_ceroActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "3");        if (auxiliar.equals ("0")){        pantalla.setText("3");        }        else{        pantalla.setText(auxiliar + "3");        }
    }//GEN-LAST:event_tresActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "2");        if (auxiliar.equals ("0")){        pantalla.setText("2");        }        else{        pantalla.setText(auxiliar + "2");        }
    }//GEN-LAST:event_dosActionPerformed

    private void uno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uno1ActionPerformed
      String auxiliar = pantalla.getText();        pantalla.setText(auxiliar + "1");        if (auxiliar.equals ("0")){        pantalla.setText("1");        }        else{        pantalla.setText(auxiliar + "1");        }
    }//GEN-LAST:event_uno1ActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        
        operacion = "x";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        
        operacion = "-";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_restaActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed

        operacion = "/";
        //Double.valueOf convierte un string en un número.
        operando1 = Double.valueOf(pantalla.getText());
        //Reseteo la pantalla a 0.
        pantalla.setText("0");
        
    }//GEN-LAST:event_divisionActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed

        double operando2 = Double.valueOf(pantalla.getText());
        if(operacion.equals("/")){
            operando1 = operando1 / operando2;
        }
        if(operacion.equals("x")){
            operando1 = operando1 * operando2;
        }
        if(operacion.equals("-")){
            operando1 = operando1 - operando2;
        }
        if(operacion.equals("+")){
            operando1 = operando1 + operando2;
        }
        if(operacion.equals("x-")){
            operando1 = - operando1;
        }
        if(operacion.equals("√")){
            operando1 = Math.sqrt(operando1);
        }
        if(operacion.equals("^")){
            operando1 = Math.pow(operando1, operando2);
        }
        if(operacion.equals("1/x")){
            operando1 = 1 / operando1 ;
        }
        
        pantalla.setText("" + operando1);
                
    }//GEN-LAST:event_igualActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed

        operacion = "+";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_sumaActionPerformed

    private void comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaActionPerformed
       
       String auxiliar = pantalla.getText();
        if (auxiliar.equals("0")) {
            pantalla.setText(".");
        } else {
            pantalla.setText(auxiliar + ".");
        }
    }//GEN-LAST:event_comaActionPerformed

    private void signoCambiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoCambiadoActionPerformed
        
        operacion = "x-";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_signoCambiadoActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        
        operacion = "√";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_raizActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        
        operacion = "^";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_potenciaActionPerformed

    private void inversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inversaActionPerformed
        
        operacion = "1/x";
        operando1 = Double.valueOf(pantalla.getText());
        pantalla.setText("0");
        
    }//GEN-LAST:event_inversaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton coma;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton division;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JButton inversa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton potencia;
    private javax.swing.JButton raiz;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton signoCambiado;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno1;
    // End of variables declaration//GEN-END:variables
}
